In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

In [4]:
model = LogisticRegression(max_iter=1000)
l_scores = cross_val_score(model, iris.data, iris.target)
print(l_scores)

[0.96666667 1.         0.93333333 0.96666667 1.        ]


In [5]:
np.average(l_scores)

np.float64(0.9733333333333334)

In [6]:
#decision tree
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [7]:
np.average(d_scores)

np.float64(0.9666666666666668)

In [8]:
#svm
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [9]:

np.average(s_scores)

np.float64(0.9666666666666666)

In [10]:
#random forest
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [11]:
np.average(r_scores)

np.float64(0.9666666666666668)